DROP TABLE CLASS CASCADE;
DROP TABLE corequisite CASCADE;
DROP TABLE department CASCADE;
DROP TABLE professor CASCADE;
DROP TABLE coursedept CASCADE;
DROP TABLE courseoff CASCADE;
DROP TABLE courseprof CASCADE;
DROP TABLE schedule CASCADE;