"""empty message

Revision ID: 2e68164a73a9
Revises: e027e0450d70
Create Date: 2020-03-24 23:32:34.221793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e68164a73a9'
down_revision = 'e027e0450d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseofftest',
    sa.Column('course_name', sa.String(length=256), nullable=False),
    sa.Column('course_type', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_name', 'course_type', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseofftest')
    # ### end Alembic commands ###
