"""empty message

Revision ID: 19460b67bc7e
Revises: 233ada81cc9d
Create Date: 2020-03-29 01:39:46.138556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19460b67bc7e'
down_revision = '233ada81cc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courseprof',
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('course_num', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(precision=2, asdecimal=1), nullable=True),
    sa.ForeignKeyConstraint(['prof_id'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['subject', 'course_num', 'type', 'id'], ['courseoff.subject', 'courseoff.course_num', 'courseoff.type', 'courseoff.id'], ),
    sa.PrimaryKeyConstraint('subject', 'course_num', 'type', 'id', 'prof_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseprof')
    op.drop_table('professor')
    # ### end Alembic commands ###
