"""empty message

Revision ID: 430e1e04753b
Revises: e6d8ccbfb29d
Create Date: 2020-03-24 22:50:23.344042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430e1e04753b'
down_revision = 'e6d8ccbfb29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseoffTest',
    sa.Column('course_name', sa.String(length=256), nullable=False),
    sa.Column('course_type', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_name', 'course_type', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseoffTest')
    # ### end Alembic commands ###
