"""empty message

Revision ID: 8a7f64995e70
Revises: 430e1e04753b
Create Date: 2020-03-24 22:54:09.890483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7f64995e70'
down_revision = '430e1e04753b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseofftest',
    sa.Column('course_name', sa.String(length=256), nullable=False),
    sa.Column('course_type', sa.String(length=256), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('course_name', 'course_type', 'course_id')
    )
    op.drop_table('courseoffTest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseoffTest',
    sa.Column('course_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('course_type', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('course_name', 'course_type', 'course_id', name='courseoffTest_pkey')
    )
    op.drop_table('courseofftest')
    # ### end Alembic commands ###
